// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: ghidra.proto

package ghidra

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Permission int32

const (
	Permission_READ_ONLY Permission = 0
	Permission_WRITE     Permission = 1
	Permission_ADMIN     Permission = 2
	Permission_NONE      Permission = -2
)

// Enum value maps for Permission.
var (
	Permission_name = map[int32]string{
		0:  "READ_ONLY",
		1:  "WRITE",
		2:  "ADMIN",
		-2: "NONE",
	}
	Permission_value = map[string]int32{
		"READ_ONLY": 0,
		"WRITE":     1,
		"ADMIN":     2,
		"NONE":      -2,
	}
)

func (x Permission) Enum() *Permission {
	p := new(Permission)
	*p = x
	return p
}

func (x Permission) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Permission) Descriptor() protoreflect.EnumDescriptor {
	return file_ghidra_proto_enumTypes[0].Descriptor()
}

func (Permission) Type() protoreflect.EnumType {
	return &file_ghidra_proto_enumTypes[0]
}

func (x Permission) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Permission.Descriptor instead.
func (Permission) EnumDescriptor() ([]byte, []int) {
	return file_ghidra_proto_rawDescGZIP(), []int{0}
}

type Version struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	GhidraVersion      string                 `protobuf:"bytes,1,opt,name=ghidraVersion,proto3" json:"ghidraVersion,omitempty"`
	GhidraPanelVersion string                 `protobuf:"bytes,2,opt,name=ghidraPanelVersion,proto3" json:"ghidraPanelVersion,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Version) Reset() {
	*x = Version{}
	mi := &file_ghidra_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version) ProtoMessage() {}

func (x *Version) ProtoReflect() protoreflect.Message {
	mi := &file_ghidra_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version.ProtoReflect.Descriptor instead.
func (*Version) Descriptor() ([]byte, []int) {
	return file_ghidra_proto_rawDescGZIP(), []int{0}
}

func (x *Version) GetGhidraVersion() string {
	if x != nil {
		return x.GhidraVersion
	}
	return ""
}

func (x *Version) GetGhidraPanelVersion() string {
	if x != nil {
		return x.GhidraPanelVersion
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	HasPassword   bool                   `protobuf:"varint,2,opt,name=hasPassword,proto3" json:"hasPassword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_ghidra_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_ghidra_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_ghidra_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetHasPassword() bool {
	if x != nil {
		return x.HasPassword
	}
	return false
}

type UserWithPermission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Permission    Permission             `protobuf:"varint,2,opt,name=permission,proto3,enum=ghidra.Permission" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserWithPermission) Reset() {
	*x = UserWithPermission{}
	mi := &file_ghidra_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserWithPermission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserWithPermission) ProtoMessage() {}

func (x *UserWithPermission) ProtoReflect() protoreflect.Message {
	mi := &file_ghidra_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserWithPermission.ProtoReflect.Descriptor instead.
func (*UserWithPermission) Descriptor() ([]byte, []int) {
	return file_ghidra_proto_rawDescGZIP(), []int{2}
}

func (x *UserWithPermission) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UserWithPermission) GetPermission() Permission {
	if x != nil {
		return x.Permission
	}
	return Permission_READ_ONLY
}

type RepositoryStats struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SizeBytes        int64                  `protobuf:"varint,1,opt,name=sizeBytes,proto3" json:"sizeBytes,omitempty"`               // Total size in bytes
	CreatedTime      int64                  `protobuf:"varint,2,opt,name=createdTime,proto3" json:"createdTime,omitempty"`           // Creation timestamp (Unix epoch millis)
	LastModifiedTime int64                  `protobuf:"varint,3,opt,name=lastModifiedTime,proto3" json:"lastModifiedTime,omitempty"` // Last modified timestamp (Unix epoch millis)
	FileCount        int32                  `protobuf:"varint,4,opt,name=fileCount,proto3" json:"fileCount,omitempty"`               // Number of files/items in repository
	UserCount        int32                  `protobuf:"varint,5,opt,name=userCount,proto3" json:"userCount,omitempty"`               // Number of users with access
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RepositoryStats) Reset() {
	*x = RepositoryStats{}
	mi := &file_ghidra_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepositoryStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepositoryStats) ProtoMessage() {}

func (x *RepositoryStats) ProtoReflect() protoreflect.Message {
	mi := &file_ghidra_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepositoryStats.ProtoReflect.Descriptor instead.
func (*RepositoryStats) Descriptor() ([]byte, []int) {
	return file_ghidra_proto_rawDescGZIP(), []int{3}
}

func (x *RepositoryStats) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *RepositoryStats) GetCreatedTime() int64 {
	if x != nil {
		return x.CreatedTime
	}
	return 0
}

func (x *RepositoryStats) GetLastModifiedTime() int64 {
	if x != nil {
		return x.LastModifiedTime
	}
	return 0
}

func (x *RepositoryStats) GetFileCount() int32 {
	if x != nil {
		return x.FileCount
	}
	return 0
}

func (x *RepositoryStats) GetUserCount() int32 {
	if x != nil {
		return x.UserCount
	}
	return 0
}

type Repository struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Name                   string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path                   string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	AnonymousAccessAllowed bool                   `protobuf:"varint,3,opt,name=anonymousAccessAllowed,proto3" json:"anonymousAccessAllowed,omitempty"`
	Users                  []*UserWithPermission  `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty"`
	Stats                  *RepositoryStats       `protobuf:"bytes,5,opt,name=stats,proto3" json:"stats,omitempty"` // Repository statistics (may be null if not requested/available)
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Repository) Reset() {
	*x = Repository{}
	mi := &file_ghidra_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repository) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repository) ProtoMessage() {}

func (x *Repository) ProtoReflect() protoreflect.Message {
	mi := &file_ghidra_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repository.ProtoReflect.Descriptor instead.
func (*Repository) Descriptor() ([]byte, []int) {
	return file_ghidra_proto_rawDescGZIP(), []int{4}
}

func (x *Repository) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Repository) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Repository) GetAnonymousAccessAllowed() bool {
	if x != nil {
		return x.AnonymousAccessAllowed
	}
	return false
}

func (x *Repository) GetUsers() []*UserWithPermission {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *Repository) GetStats() *RepositoryStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type GetRepositoriesReply struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Version         *Version               `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	RepositoriesDir string                 `protobuf:"bytes,2,opt,name=repositoriesDir,proto3" json:"repositoriesDir,omitempty"`
	Repositories    []*Repository          `protobuf:"bytes,3,rep,name=repositories,proto3" json:"repositories,omitempty"`
	Users           []*User                `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetRepositoriesReply) Reset() {
	*x = GetRepositoriesReply{}
	mi := &file_ghidra_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepositoriesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepositoriesReply) ProtoMessage() {}

func (x *GetRepositoriesReply) ProtoReflect() protoreflect.Message {
	mi := &file_ghidra_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepositoriesReply.ProtoReflect.Descriptor instead.
func (*GetRepositoriesReply) Descriptor() ([]byte, []int) {
	return file_ghidra_proto_rawDescGZIP(), []int{5}
}

func (x *GetRepositoriesReply) GetVersion() *Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *GetRepositoriesReply) GetRepositoriesDir() string {
	if x != nil {
		return x.RepositoriesDir
	}
	return ""
}

func (x *GetRepositoriesReply) GetRepositories() []*Repository {
	if x != nil {
		return x.Repositories
	}
	return nil
}

func (x *GetRepositoriesReply) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type GetRepositoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repository    string                 `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepositoryRequest) Reset() {
	*x = GetRepositoryRequest{}
	mi := &file_ghidra_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepositoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepositoryRequest) ProtoMessage() {}

func (x *GetRepositoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ghidra_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepositoryRequest.ProtoReflect.Descriptor instead.
func (*GetRepositoryRequest) Descriptor() ([]byte, []int) {
	return file_ghidra_proto_rawDescGZIP(), []int{6}
}

func (x *GetRepositoryRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

type GetRepositoryReply struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Version         *Version               `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	RepositoriesDir string                 `protobuf:"bytes,2,opt,name=repositoriesDir,proto3" json:"repositoriesDir,omitempty"`
	Repository      *Repository            `protobuf:"bytes,3,opt,name=repository,proto3" json:"repository,omitempty"`
	Users           []*User                `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetRepositoryReply) Reset() {
	*x = GetRepositoryReply{}
	mi := &file_ghidra_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepositoryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepositoryReply) ProtoMessage() {}

func (x *GetRepositoryReply) ProtoReflect() protoreflect.Message {
	mi := &file_ghidra_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepositoryReply.ProtoReflect.Descriptor instead.
func (*GetRepositoryReply) Descriptor() ([]byte, []int) {
	return file_ghidra_proto_rawDescGZIP(), []int{7}
}

func (x *GetRepositoryReply) GetVersion() *Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *GetRepositoryReply) GetRepositoriesDir() string {
	if x != nil {
		return x.RepositoriesDir
	}
	return ""
}

func (x *GetRepositoryReply) GetRepository() *Repository {
	if x != nil {
		return x.Repository
	}
	return nil
}

func (x *GetRepositoryReply) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type GetRepositoryUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Repository    string                 `protobuf:"bytes,2,opt,name=repository,proto3" json:"repository,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepositoryUserRequest) Reset() {
	*x = GetRepositoryUserRequest{}
	mi := &file_ghidra_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepositoryUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepositoryUserRequest) ProtoMessage() {}

func (x *GetRepositoryUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ghidra_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepositoryUserRequest.ProtoReflect.Descriptor instead.
func (*GetRepositoryUserRequest) Descriptor() ([]byte, []int) {
	return file_ghidra_proto_rawDescGZIP(), []int{8}
}

func (x *GetRepositoryUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetRepositoryUserRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

type GetRepositoryUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *UserWithPermission    `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepositoryUserReply) Reset() {
	*x = GetRepositoryUserReply{}
	mi := &file_ghidra_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepositoryUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepositoryUserReply) ProtoMessage() {}

func (x *GetRepositoryUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_ghidra_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepositoryUserReply.ProtoReflect.Descriptor instead.
func (*GetRepositoryUserReply) Descriptor() ([]byte, []int) {
	return file_ghidra_proto_rawDescGZIP(), []int{9}
}

func (x *GetRepositoryUserReply) GetResult() *UserWithPermission {
	if x != nil {
		return x.Result
	}
	return nil
}

type GetUsersReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersReply) Reset() {
	*x = GetUsersReply{}
	mi := &file_ghidra_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersReply) ProtoMessage() {}

func (x *GetUsersReply) ProtoReflect() protoreflect.Message {
	mi := &file_ghidra_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersReply.ProtoReflect.Descriptor instead.
func (*GetUsersReply) Descriptor() ([]byte, []int) {
	return file_ghidra_proto_rawDescGZIP(), []int{10}
}

func (x *GetUsersReply) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type AddUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserRequest) Reset() {
	*x = AddUserRequest{}
	mi := &file_ghidra_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserRequest) ProtoMessage() {}

func (x *AddUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ghidra_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserRequest.ProtoReflect.Descriptor instead.
func (*AddUserRequest) Descriptor() ([]byte, []int) {
	return file_ghidra_proto_rawDescGZIP(), []int{11}
}

func (x *AddUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type RemoveUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserRequest) Reset() {
	*x = RemoveUserRequest{}
	mi := &file_ghidra_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserRequest) ProtoMessage() {}

func (x *RemoveUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ghidra_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserRequest.ProtoReflect.Descriptor instead.
func (*RemoveUserRequest) Descriptor() ([]byte, []int) {
	return file_ghidra_proto_rawDescGZIP(), []int{12}
}

func (x *RemoveUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type SetUserPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Repository    string                 `protobuf:"bytes,2,opt,name=repository,proto3" json:"repository,omitempty"`
	Permission    Permission             `protobuf:"varint,3,opt,name=permission,proto3,enum=ghidra.Permission" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserPermissionRequest) Reset() {
	*x = SetUserPermissionRequest{}
	mi := &file_ghidra_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserPermissionRequest) ProtoMessage() {}

func (x *SetUserPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ghidra_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserPermissionRequest.ProtoReflect.Descriptor instead.
func (*SetUserPermissionRequest) Descriptor() ([]byte, []int) {
	return file_ghidra_proto_rawDescGZIP(), []int{13}
}

func (x *SetUserPermissionRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SetUserPermissionRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *SetUserPermissionRequest) GetPermission() Permission {
	if x != nil {
		return x.Permission
	}
	return Permission_READ_ONLY
}

type AuthenticateUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Username to authenticate (case-insensitive)
	// Reply will contain the actual username
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// Password to authenticate
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateUserRequest) Reset() {
	*x = AuthenticateUserRequest{}
	mi := &file_ghidra_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateUserRequest) ProtoMessage() {}

func (x *AuthenticateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ghidra_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateUserRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateUserRequest) Descriptor() ([]byte, []int) {
	return file_ghidra_proto_rawDescGZIP(), []int{14}
}

func (x *AuthenticateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthenticateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthenticateUserReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the authentication was successful
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Attempted username, if empty, no matching user was found
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// If success is false, this will contain the reason
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateUserReply) Reset() {
	*x = AuthenticateUserReply{}
	mi := &file_ghidra_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateUserReply) ProtoMessage() {}

func (x *AuthenticateUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_ghidra_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateUserReply.ProtoReflect.Descriptor instead.
func (*AuthenticateUserReply) Descriptor() ([]byte, []int) {
	return file_ghidra_proto_rawDescGZIP(), []int{15}
}

func (x *AuthenticateUserReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuthenticateUserReply) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthenticateUserReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteRepositoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repository    string                 `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRepositoryRequest) Reset() {
	*x = DeleteRepositoryRequest{}
	mi := &file_ghidra_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRepositoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRepositoryRequest) ProtoMessage() {}

func (x *DeleteRepositoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ghidra_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRepositoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteRepositoryRequest) Descriptor() ([]byte, []int) {
	return file_ghidra_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteRepositoryRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

var File_ghidra_proto protoreflect.FileDescriptor

const file_ghidra_proto_rawDesc = "" +
	"\n" +
	"\fghidra.proto\x12\x06ghidra\x1a\x1bgoogle/protobuf/empty.proto\"_\n" +
	"\aVersion\x12$\n" +
	"\rghidraVersion\x18\x01 \x01(\tR\rghidraVersion\x12.\n" +
	"\x12ghidraPanelVersion\x18\x02 \x01(\tR\x12ghidraPanelVersion\"D\n" +
	"\x04User\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12 \n" +
	"\vhasPassword\x18\x02 \x01(\bR\vhasPassword\"j\n" +
	"\x12UserWithPermission\x12 \n" +
	"\x04user\x18\x01 \x01(\v2\f.ghidra.UserR\x04user\x122\n" +
	"\n" +
	"permission\x18\x02 \x01(\x0e2\x12.ghidra.PermissionR\n" +
	"permission\"\xb9\x01\n" +
	"\x0fRepositoryStats\x12\x1c\n" +
	"\tsizeBytes\x18\x01 \x01(\x03R\tsizeBytes\x12 \n" +
	"\vcreatedTime\x18\x02 \x01(\x03R\vcreatedTime\x12*\n" +
	"\x10lastModifiedTime\x18\x03 \x01(\x03R\x10lastModifiedTime\x12\x1c\n" +
	"\tfileCount\x18\x04 \x01(\x05R\tfileCount\x12\x1c\n" +
	"\tuserCount\x18\x05 \x01(\x05R\tuserCount\"\xcd\x01\n" +
	"\n" +
	"Repository\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x126\n" +
	"\x16anonymousAccessAllowed\x18\x03 \x01(\bR\x16anonymousAccessAllowed\x120\n" +
	"\x05users\x18\x04 \x03(\v2\x1a.ghidra.UserWithPermissionR\x05users\x12-\n" +
	"\x05stats\x18\x05 \x01(\v2\x17.ghidra.RepositoryStatsR\x05stats\"\xc7\x01\n" +
	"\x14GetRepositoriesReply\x12)\n" +
	"\aversion\x18\x01 \x01(\v2\x0f.ghidra.VersionR\aversion\x12(\n" +
	"\x0frepositoriesDir\x18\x02 \x01(\tR\x0frepositoriesDir\x126\n" +
	"\frepositories\x18\x03 \x03(\v2\x12.ghidra.RepositoryR\frepositories\x12\"\n" +
	"\x05users\x18\x04 \x03(\v2\f.ghidra.UserR\x05users\"6\n" +
	"\x14GetRepositoryRequest\x12\x1e\n" +
	"\n" +
	"repository\x18\x01 \x01(\tR\n" +
	"repository\"\xc1\x01\n" +
	"\x12GetRepositoryReply\x12)\n" +
	"\aversion\x18\x01 \x01(\v2\x0f.ghidra.VersionR\aversion\x12(\n" +
	"\x0frepositoriesDir\x18\x02 \x01(\tR\x0frepositoriesDir\x122\n" +
	"\n" +
	"repository\x18\x03 \x01(\v2\x12.ghidra.RepositoryR\n" +
	"repository\x12\"\n" +
	"\x05users\x18\x04 \x03(\v2\f.ghidra.UserR\x05users\"V\n" +
	"\x18GetRepositoryUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1e\n" +
	"\n" +
	"repository\x18\x02 \x01(\tR\n" +
	"repository\"L\n" +
	"\x16GetRepositoryUserReply\x122\n" +
	"\x06result\x18\x01 \x01(\v2\x1a.ghidra.UserWithPermissionR\x06result\"3\n" +
	"\rGetUsersReply\x12\"\n" +
	"\x05users\x18\x01 \x03(\v2\f.ghidra.UserR\x05users\",\n" +
	"\x0eAddUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"/\n" +
	"\x11RemoveUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"\x8a\x01\n" +
	"\x18SetUserPermissionRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1e\n" +
	"\n" +
	"repository\x18\x02 \x01(\tR\n" +
	"repository\x122\n" +
	"\n" +
	"permission\x18\x03 \x01(\x0e2\x12.ghidra.PermissionR\n" +
	"permission\"Q\n" +
	"\x17AuthenticateUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"g\n" +
	"\x15AuthenticateUserReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"9\n" +
	"\x17DeleteRepositoryRequest\x12\x1e\n" +
	"\n" +
	"repository\x18\x01 \x01(\tR\n" +
	"repository*D\n" +
	"\n" +
	"Permission\x12\r\n" +
	"\tREAD_ONLY\x10\x00\x12\t\n" +
	"\x05WRITE\x10\x01\x12\t\n" +
	"\x05ADMIN\x10\x02\x12\x11\n" +
	"\x04NONE\x10\xfe\xff\xff\xff\xff\xff\xff\xff\xff\x012\xe5\x05\n" +
	"\x06Ghidra\x127\n" +
	"\n" +
	"GetVersion\x12\x16.google.protobuf.Empty\x1a\x0f.ghidra.Version\"\x00\x12I\n" +
	"\x0fGetRepositories\x12\x16.google.protobuf.Empty\x1a\x1c.ghidra.GetRepositoriesReply\"\x00\x12K\n" +
	"\rGetRepository\x12\x1c.ghidra.GetRepositoryRequest\x1a\x1a.ghidra.GetRepositoryReply\"\x00\x12W\n" +
	"\x11GetRepositoryUser\x12 .ghidra.GetRepositoryUserRequest\x1a\x1e.ghidra.GetRepositoryUserReply\"\x00\x12;\n" +
	"\bGetUsers\x12\x16.google.protobuf.Empty\x1a\x15.ghidra.GetUsersReply\"\x00\x12;\n" +
	"\aAddUser\x12\x16.ghidra.AddUserRequest\x1a\x16.google.protobuf.Empty\"\x00\x12A\n" +
	"\n" +
	"RemoveUser\x12\x19.ghidra.RemoveUserRequest\x1a\x16.google.protobuf.Empty\"\x00\x12O\n" +
	"\x11SetUserPermission\x12 .ghidra.SetUserPermissionRequest\x1a\x16.google.protobuf.Empty\"\x00\x12T\n" +
	"\x10AuthenticateUser\x12\x1f.ghidra.AuthenticateUserRequest\x1a\x1d.ghidra.AuthenticateUserReply\"\x00\x12M\n" +
	"\x10DeleteRepository\x12\x1f.ghidra.DeleteRepositoryRequest\x1a\x16.google.protobuf.Empty\"\x00BD\n" +
	"\x14re.mkw.srejaas.protoB\vGhidraProtoP\x01Z\x1dgo.mkw.re/ghidra-panel/ghidrab\x06proto3"

var (
	file_ghidra_proto_rawDescOnce sync.Once
	file_ghidra_proto_rawDescData []byte
)

func file_ghidra_proto_rawDescGZIP() []byte {
	file_ghidra_proto_rawDescOnce.Do(func() {
		file_ghidra_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ghidra_proto_rawDesc), len(file_ghidra_proto_rawDesc)))
	})
	return file_ghidra_proto_rawDescData
}

var file_ghidra_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ghidra_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_ghidra_proto_goTypes = []any{
	(Permission)(0),                  // 0: ghidra.Permission
	(*Version)(nil),                  // 1: ghidra.Version
	(*User)(nil),                     // 2: ghidra.User
	(*UserWithPermission)(nil),       // 3: ghidra.UserWithPermission
	(*RepositoryStats)(nil),          // 4: ghidra.RepositoryStats
	(*Repository)(nil),               // 5: ghidra.Repository
	(*GetRepositoriesReply)(nil),     // 6: ghidra.GetRepositoriesReply
	(*GetRepositoryRequest)(nil),     // 7: ghidra.GetRepositoryRequest
	(*GetRepositoryReply)(nil),       // 8: ghidra.GetRepositoryReply
	(*GetRepositoryUserRequest)(nil), // 9: ghidra.GetRepositoryUserRequest
	(*GetRepositoryUserReply)(nil),   // 10: ghidra.GetRepositoryUserReply
	(*GetUsersReply)(nil),            // 11: ghidra.GetUsersReply
	(*AddUserRequest)(nil),           // 12: ghidra.AddUserRequest
	(*RemoveUserRequest)(nil),        // 13: ghidra.RemoveUserRequest
	(*SetUserPermissionRequest)(nil), // 14: ghidra.SetUserPermissionRequest
	(*AuthenticateUserRequest)(nil),  // 15: ghidra.AuthenticateUserRequest
	(*AuthenticateUserReply)(nil),    // 16: ghidra.AuthenticateUserReply
	(*DeleteRepositoryRequest)(nil),  // 17: ghidra.DeleteRepositoryRequest
	(*emptypb.Empty)(nil),            // 18: google.protobuf.Empty
}
var file_ghidra_proto_depIdxs = []int32{
	2,  // 0: ghidra.UserWithPermission.user:type_name -> ghidra.User
	0,  // 1: ghidra.UserWithPermission.permission:type_name -> ghidra.Permission
	3,  // 2: ghidra.Repository.users:type_name -> ghidra.UserWithPermission
	4,  // 3: ghidra.Repository.stats:type_name -> ghidra.RepositoryStats
	1,  // 4: ghidra.GetRepositoriesReply.version:type_name -> ghidra.Version
	5,  // 5: ghidra.GetRepositoriesReply.repositories:type_name -> ghidra.Repository
	2,  // 6: ghidra.GetRepositoriesReply.users:type_name -> ghidra.User
	1,  // 7: ghidra.GetRepositoryReply.version:type_name -> ghidra.Version
	5,  // 8: ghidra.GetRepositoryReply.repository:type_name -> ghidra.Repository
	2,  // 9: ghidra.GetRepositoryReply.users:type_name -> ghidra.User
	3,  // 10: ghidra.GetRepositoryUserReply.result:type_name -> ghidra.UserWithPermission
	2,  // 11: ghidra.GetUsersReply.users:type_name -> ghidra.User
	0,  // 12: ghidra.SetUserPermissionRequest.permission:type_name -> ghidra.Permission
	18, // 13: ghidra.Ghidra.GetVersion:input_type -> google.protobuf.Empty
	18, // 14: ghidra.Ghidra.GetRepositories:input_type -> google.protobuf.Empty
	7,  // 15: ghidra.Ghidra.GetRepository:input_type -> ghidra.GetRepositoryRequest
	9,  // 16: ghidra.Ghidra.GetRepositoryUser:input_type -> ghidra.GetRepositoryUserRequest
	18, // 17: ghidra.Ghidra.GetUsers:input_type -> google.protobuf.Empty
	12, // 18: ghidra.Ghidra.AddUser:input_type -> ghidra.AddUserRequest
	13, // 19: ghidra.Ghidra.RemoveUser:input_type -> ghidra.RemoveUserRequest
	14, // 20: ghidra.Ghidra.SetUserPermission:input_type -> ghidra.SetUserPermissionRequest
	15, // 21: ghidra.Ghidra.AuthenticateUser:input_type -> ghidra.AuthenticateUserRequest
	17, // 22: ghidra.Ghidra.DeleteRepository:input_type -> ghidra.DeleteRepositoryRequest
	1,  // 23: ghidra.Ghidra.GetVersion:output_type -> ghidra.Version
	6,  // 24: ghidra.Ghidra.GetRepositories:output_type -> ghidra.GetRepositoriesReply
	8,  // 25: ghidra.Ghidra.GetRepository:output_type -> ghidra.GetRepositoryReply
	10, // 26: ghidra.Ghidra.GetRepositoryUser:output_type -> ghidra.GetRepositoryUserReply
	11, // 27: ghidra.Ghidra.GetUsers:output_type -> ghidra.GetUsersReply
	18, // 28: ghidra.Ghidra.AddUser:output_type -> google.protobuf.Empty
	18, // 29: ghidra.Ghidra.RemoveUser:output_type -> google.protobuf.Empty
	18, // 30: ghidra.Ghidra.SetUserPermission:output_type -> google.protobuf.Empty
	16, // 31: ghidra.Ghidra.AuthenticateUser:output_type -> ghidra.AuthenticateUserReply
	18, // 32: ghidra.Ghidra.DeleteRepository:output_type -> google.protobuf.Empty
	23, // [23:33] is the sub-list for method output_type
	13, // [13:23] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_ghidra_proto_init() }
func file_ghidra_proto_init() {
	if File_ghidra_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ghidra_proto_rawDesc), len(file_ghidra_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ghidra_proto_goTypes,
		DependencyIndexes: file_ghidra_proto_depIdxs,
		EnumInfos:         file_ghidra_proto_enumTypes,
		MessageInfos:      file_ghidra_proto_msgTypes,
	}.Build()
	File_ghidra_proto = out.File
	file_ghidra_proto_goTypes = nil
	file_ghidra_proto_depIdxs = nil
}
